server:
  port: 19090
spring:
  security:
    user:
      name: admin
      password: password
  boot:
    admin:
      client:
        username: ${spring.security.user.name}
        password: ${spring.security.user.password}
